/-
  System-level invariants of private-games, proved through the property
  kernel (PLAN.md M8 demonstrator). Until now these were only checked at
  runtime by the repository:

  1. `allValid`: every stored game is `Valid`.
  2. `uniqueIds`: game ids are unique. This needs the strengthening
     `Fresh` (every id is below `nextGame`), found as the counterexample to
     induction `ListStore.unique_cti` (PROPERTIES.md §6.5).

  How: the model (`gamesApp.toSys`) simulates the generic `ListStore` of
  games, whose writers are the domain decisions themselves: `create` is
  `openGame` and `apply` is `decide`. The store has no validity guard, so
  the store's obligations are exactly the domain's preservation theorems
  generated by `preserves` (`Valid.preserved_openGame`, `…_playMove`,
  `…_resign`). The simulation obligation is a fact about `core`: every
  write it plans is the result of a domain decision (`core_writeOk`).

  The model's commit still re-checks `Valid.holdsB` at runtime (defense in
  depth, as the native transaction does), but `allValid` does not rely on
  it: a decision that produced an invalid game would break the build here
  (review H1, eb67460).
-/
import LeanApi.Props.Bridge
import LeanApi.Props.Store
import PrivateGames.Model.Generic

namespace PrivateGames.Model

open LeanApi LeanApi.Props LeanApi.Proofs PrivateGames.App

/-! ## The store of games -/

/-- Games as a generic list store whose writers are the domain decisions:
    `create` opens a game with the store's next id, and `apply` runs
    `decide` for an actor and a command. No validity guard. -/
def gameStore : ListStore where
  Entity := Game
  Create := PlayerId × PlayerId × TimeControl
  Cmd := PlayerId × Command
  Err := DomainError
  id g := g.id.n
  create n c := openGame ⟨n⟩ c.1 c.2.1 c.2.2
  apply c g := PrivateGames.decide c.1 g c.2

/-- The store's obligations are the domain's preservation theorems. -/
theorem gameStore_preserves : gameStore.Preserves Valid where
  create n c x h := Valid.preserved_openGame _ _ _ _ _ h
  apply c x y hx h := by
    obtain ⟨p, cmd⟩ := c
    cases cmd with
    | play e cell => exact Valid.preserved_playMove p e cell x y hx h
    | resign => exact Valid.preserved_resign p x y hx h

theorem playMove_id {p : PlayerId} {e : Revision} {c : Cell} {g g' : Game}
    (h : PrivateGames.playMove p e c g = .ok g') : g'.id = g.id := by
  obtain ⟨_, _, _, _, _, rfl⟩ := playMove_ok h; rfl

theorem resign_id {p : PlayerId} {g g' : Game} (h : PrivateGames.resign p g = .ok g') : g'.id = g.id := by
  obtain ⟨_, hc⟩ := resign_ok h
  rcases hc with ⟨_, rfl⟩ | ⟨_, _, rfl⟩ <;> rfl

theorem openGame_id {id : GameId} {p o : PlayerId} {tc : TimeControl} {g : Game}
    (h : openGame id p o tc = .ok g) : g.id = id := by
  unfold openGame at h
  split at h
  · cases h
  · cases h; rfl

theorem gameStore_idLaws : gameStore.IdLaws where
  create n c x h := congrArg GameId.n (openGame_id h)
  apply c x y h := by
    obtain ⟨p, cmd⟩ := c
    cases cmd with
    | play e cell => exact congrArg GameId.n (playMove_id h)
    | resign => exact congrArg GameId.n (resign_id h)

/-! ## What `core` plans -/

/-- The writes `core` may plan: each is the result of a domain decision.
    An insert is a game `openGame` produced (the model assigns its id), and
    an update is what `decide` produced from the game it replaces. -/
def WriteOk : Write → Prop
  | .insertGame g => ∃ c : gameStore.Create, openGame ⟨0⟩ c.1 c.2.1 c.2.2 = .ok g
  | .updateGame old new => ∃ c : gameStore.Cmd, PrivateGames.decide c.1 old c.2 = .ok new

theorem decideCore_writeOk {p : PlayerId} {i : Input} {s : Slice} {wr : Write} {b : Game → Res}
    (h : decideCore p i s = .write wr b) : WriteOk wr := by
  cases i with
  | readGame _ => simp only [decideCore] at h; split at h <;> cases h
  | listGames _ _ => simp only [decideCore] at h; cases h
  | openGame opp tc _ =>
    simp only [decideCore] at h
    split at h
    · cases h
    · split at h
      · cases h
      · rename_i g hg; cases h; exact ⟨(p, opp, tc), hg⟩
  | playMove _ rev cell _ =>
    simp only [decideCore] at h
    split at h
    · cases h
    · split at h
      · cases h
      · rename_i g _ g' hg; cases h; exact ⟨(p, .play rev cell), hg⟩
  | resign _ _ =>
    simp only [decideCore] at h
    split at h
    · cases h
    · split at h
      · cases h
      · rename_i g _ g' hg
        split at h
        · cases h
        · cases h; exact ⟨(p, .resign), hg⟩

theorem core_writeOk {p : PlayerId} {i : Input} {s : Slice} {wr : Write} {k : Option Keyed} {b : Game → Res}
    (h : core p i s = .write wr k b) : WriteOk wr := by
  simp only [core, withReceipt] at h
  split at h
  · split at h <;> cases h
  · split at h
    · cases h
    · rename_i wr' b' hd; cases h; exact decideCore_writeOk hd

/-! ## The simulation -/

def toStore (w : World) : gameStore.World := { items := w.games, next := w.nextGame }

/-- The model world starts with no games. Sessions, players and receipts
    may start anywhere. -/
def gamesInit (w : World) : Prop := w.games = []

def gamesSys : Sys := gamesApp.toSys gamesInit

theorem toStore_record (p : PlayerId) (k : Option Keyed) (res : Res) (w : World) :
    toStore (recordReceipt p k res w) = toStore w := by
  cases k <;> rfl

theorem commit_sim (p : PlayerId) (wr : Write) (k : Option Keyed) (b : Game → Res) (w : World)
    (hw : WriteOk wr) :
    toStore (commit p wr k b w).2 = toStore w ∨
      ∃ r, toStore (commit p wr k b w).2 = (gameStore.step r (toStore w)).2 := by
  cases wr with
  | insertGame g =>
    obtain ⟨c, hc⟩ := hw
    refine .inr ⟨.create c, ?_⟩
    have hg : openGame ⟨w.nextGame⟩ c.1 c.2.1 c.2.2 = .ok { g with id := ⟨w.nextGame⟩ } := by
      unfold openGame at hc ⊢
      split at hc
      · cases hc
      · rename_i hne; cases hc; simp [hne, Game.opened]
    simp only [commit, toStore_record]
    simp only [toStore, ListStore.step, gameStore, hg]
    rfl
  | updateGame old new =>
    obtain ⟨c, hc⟩ := hw
    simp only [commit]
    split
    · refine .inr ⟨.update old c, ?_⟩
      rw [toStore_record]
      simp only [toStore, ListStore.step, gameStore, hc, ListStore.replace]
      congr 2
    · exact .inl rfl

theorem gamesSys_sim : Simulation gamesSys gameStore.sys toStore where
  init w h := h
  step e r w := by
    show toStore (gamesApp.step r w).2 = toStore w ∨
      ∃ e' r', toStore (gamesApp.step r w).2 = (gameStore.step r' (toStore w)).2
    simp only [ScopedApp.step]
    split
    · exact .inl rfl
    · simp only [ScopedApp.operate]
      split
      · exact .inl rfl
      · rename_i p _
        split
        · exact .inl rfl
        · rename_i i _
          change toStore (runPlan p (core p i (load p w i.need)) w).2 = toStore w ∨
            ∃ e' r', toStore (runPlan p (core p i (load p w i.need)) w).2 = (gameStore.step r' (toStore w)).2
          cases hc : core p i (load p w i.need) with
          | respond _ => exact .inl rfl
          | write wr k b =>
            rcases commit_sim p wr k b w (core_writeOk hc) with h | ⟨r', h⟩
            · exact .inl h
            · exact .inr ⟨(), r', h⟩

/-! ## The two invariants -/

/-- **Every stored game is `Valid`**, in every reachable world of the model.
    It rests on the domain's preservation theorems (`gameStore_preserves`,
    generated by `preserves`) and on `core_writeOk` (every planned write is
    a domain decision); the rest is the library's entity → store lift and
    pullback along the simulation. The commit's runtime validity check is
    not used. -/
theorem allValid : Invariant gamesSys (fun w => ∀ g ∈ w.games, Valid g) :=
  Invariant.pullback gamesSys_sim (gameStore.allOf_invariant gameStore_preserves)

/-- **Game ids are unique**, in every reachable world of the model. -/
theorem uniqueIds : Invariant gamesSys (fun w => (w.games.map (·.id.n)).Nodup) :=
  Invariant.pullback gamesSys_sim (gameStore.ids_invariant gameStore_idLaws)

/-- The strengthening is itself invariant: every id is below `nextGame`. -/
theorem freshIds : Invariant gamesSys (fun w => ∀ g ∈ w.games, g.id.n < w.nextGame) :=
  Invariant.pullback gamesSys_sim (Invariant.of_inductive (gameStore.fresh_inductive gameStore_idLaws))

/-- Uniqueness alone is not inductive for the store of games: the kernel's
    `CTI` names the world (`nextGame` equal to an existing id), and `Fresh`
    excludes it. -/
theorem uniqueIds_needs_fresh : ¬ Inductive gameStore.sys gameStore.UniqueIds :=
  gameStore.unique_not_inductive (.lit 1, .lit 2, TimeControl.default) (Game.opened ⟨0⟩ (.lit 1) (.lit 2) TimeControl.default)
    (by simp [gameStore, openGame])

end PrivateGames.Model
