import LeanApi.Core.Publish

/-! # Endpoints read off function types (portable half of DDD-LAPI-05)

```
def api : Api := [
  post "/members"             register,
  post "/books"               addBook,
  get  "/books/:book"         getBook,
  post "/books/:book/loans"   borrow
]
```

An `Api` declaration publishes each listed function (`derive_operation`), checks its
route, and generates one TYPED constant per entry, named after the function, plus the
erased list used for serving, the manifest and the allowlist. An entry with path
parameters takes them as arguments, in path order, and returns the endpoint with those
fields bound; its unbound route is `api.f.endpoint`:

```
api.addBook          : Endpoint addBook.Input Empty (Ref Book)
api.borrow           : Ref Book → Endpoint borrow.Input BorrowError (Ref Loan)
api.borrow.endpoint  : Endpoint borrow.Input BorrowError (Ref Loan)
api                  : Api := [api.register, api.addBook, api.getBook.endpoint, api.borrow.endpoint]
```

All are built from the same entries, so they cannot disagree. `get` requires a `ReadOp`;
`post` requires an `Op`. A path parameter `:name` binds the argument with that name; a
parameter with no matching argument, or bound to an argument whose type has no path codec,
is a compile error naming both. Arguments that are not path parameters (and not the actor)
come from the request body. -/

namespace LeanApi.Core
open Ontology LeanDb.Model

inductive Method where
  | get
  | post
  deriving Repr, BEq, DecidableEq

def Method.name : Method → String
  | .get => "GET"
  | .post => "POST"

/-- One published operation bound to an HTTP method and path. Typed by its request record,
closed domain error and output, so `form api.signUp` can check `onError` exhaustively. -/
structure Endpoint (Input Error Output : Type) where
  kind : Contract.OperationKind
  Actor : Type → Type
  operation : Operation kind Actor Input Output Error
  method : Method
  path : String
  /-- Input fields bound from `:name` path segments, in path order. -/
  pathParams : List String
  /-- Path fields already given (`api.borrow book`), as wire values. -/
  bound : List (String × Lean.Json) := []

/-- An endpoint with its types erased, for serving, manifests and allowlists. -/
structure AnyEndpoint where
  Input : Type
  Error : Type
  Output : Type
  endpoint : Endpoint Input Error Output

instance : CoeOut (Endpoint I E O) AnyEndpoint := ⟨fun endpoint => ⟨I, E, O, endpoint⟩⟩

/-- The routes an application serves. Only listed endpoints are routable. -/
abbrev Api := List AnyEndpoint

def AnyEndpoint.method (e : AnyEndpoint) : Method := e.endpoint.method
def AnyEndpoint.path (e : AnyEndpoint) : String := e.endpoint.path
def AnyEndpoint.identity (e : AnyEndpoint) : Contract.OperationId := e.endpoint.operation.contract.identity
def AnyEndpoint.describe (e : AnyEndpoint) : Contract.OperationInfo := e.endpoint.operation.contract.describe

/-- `/`-separated segments, by characters (portable: no byte-position string operations). -/
def pathSegments (path : String) : List String :=
  let (parts, current) := path.toList.foldl (fun (parts, current) c =>
    if c == '/' then (parts ++ [String.ofList current.reverse], []) else (parts, c :: current))
    (([] : List String), ([] : List Char))
  parts ++ [String.ofList current.reverse]

/-- The parameter name of a `:name` segment. -/
def segmentParameter? (segment : String) : Option String :=
  match segment.toList with
  | ':' :: name => some (String.ofList name)
  | _ => none

/-- `:name` segments of a path template, in order. -/
def pathParameters (path : String) : List String :=
  (pathSegments path).filterMap segmentParameter?

/-- A published function: the `Operation` derived from its type (generated by
`derive_operation`/an `Api` declaration). Indexed by the function VALUE. -/
class PublishedOperation {α : Sort u} (f : α) (kind : outParam Contract.OperationKind) (Actor : outParam (Type → Type))
    (Input Output Error : outParam Type) where
  operation : Operation kind Actor Input Output Error

/-- Marker discharged by `path_parameters` at elaboration: every `:name` of `path` is a
path-bindable field of `Input`. -/
def PathParametersBound (_path : String) (_Input : Type) : Prop := True

/-- Give the path field `name` (wire value). -/
def Endpoint.bindPath (endpoint : Endpoint I E O) (name : String) (value : Lean.Json) : Endpoint I E O :=
  { endpoint with bound := endpoint.bound.filter (·.1 != name) ++ [(name, value)] }

/-- A path field's text: a reference's integer, or a string (portable; no JSON printer). -/
def pathText : Lean.Json → String
  | .num n => if n.exponent == 0 then toString n.mantissa else "?"
  | .str text => text
  | _ => "?"

/-- The concrete path with bound fields substituted (`/books/7/loans`). -/
def Endpoint.concretePath (endpoint : Endpoint I E O) : String :=
  "/".intercalate ((pathSegments endpoint.path).map fun segment =>
    match segmentParameter? segment with
    | some name => match endpoint.bound.lookup name with
      | some value => pathText value
      | none => segment
    | none => segment)

def Endpoint.post (path : String) (operation : Operation .command A I O E) : Endpoint I E O :=
  { kind := .command, Actor := A, operation, method := .post, path, pathParams := pathParameters path }
def Endpoint.get (path : String) (operation : Operation .query A I O E) : Endpoint I E O :=
  { kind := .query, Actor := A, operation, method := .get, path, pathParams := pathParameters path }

open Lean Meta Elab in
/-- Check the path parameters of a `PathParametersBound path Input` goal. -/
elab "path_parameters" : tactic => Tactic.liftMetaTactic fun goal => do
  let target ← instantiateMVars (← goal.getType)
  let some (path, input) := (do
      guard (target.isAppOfArity ``PathParametersBound 2)
      pure (target.appFn!.appArg!, target.appArg!)) | throwError "path_parameters: unexpected goal"
  let .lit (.strVal path) ← whnf path | throwError "path_parameters: the path must be a string literal"
  let input ← whnf input
  let env ← getEnv
  let fields := match input.getAppFn with
    | .const c _ => getStructureFields env c
    | _ => #[]
  for parameter in pathParameters path do
    unless fields.contains (.mkSimple parameter) do
      throwError "path parameter `:{parameter}` in \"{path}\" has no matching argument (arguments: {fields.toList})"
  goal.assign (mkConst ``True.intro)
  return []

/-- `post "/path/:arg" f`: a read-write endpoint for the published function `f`. -/
def post {α : Sort u} (path : String) (f : α) [published : PublishedOperation f .command A I O E]
    (_bound : PathParametersBound path I := by path_parameters) : Endpoint I E O :=
  Endpoint.post path published.operation

/-- `get "/path/:arg" f`: a read-only endpoint; `f` must return a `ReadOp`. -/
def get {α : Sort u} (path : String) (f : α) [published : PublishedOperation f .query A I O E]
    (_bound : PathParametersBound path I := by path_parameters) : Endpoint I E O :=
  Endpoint.get path published.operation

end LeanApi.Core

namespace LeanApi.Core.Api
open Lean Meta Elab Command LeanDb.Model

structure Entry where
  method : Method
  path : TSyntax `str
  function : Ident

private def parseEntry (stx : Syntax) : CommandElabM (Option Entry) := do
  match stx with
  | `($method:ident $path:str $f:ident) =>
    match method.getId with
    | `post => return some ⟨.post, path, f⟩
    | `get => return some ⟨.get, path, f⟩
    | _ => return none
  | _ => return none

/-- A path-bindable argument type: an entity reference (`Ref T`). -/
private def pathBindable (type : Expr) : MetaM Bool := do
  return (← whnfR type).isAppOfArity ``Ontology.EntityId 1

/-- Publish one entry: derive the operation, check method and path, add `api.f`. -/
def declareEntry (apiName : Lean.Name) (entry : Entry) : CommandElabM Lean.Name := do
  let f ← liftCoreM <| realizeGlobalConstNoOverload entry.function
  withRef entry.function <| Publish.deriveOperation f entry.function
  let shape ← liftTermElabM <| Publish.shapeOf f
  let path := entry.path.getString
  match entry.method, shape.kind with
  | .get, .command => throwErrorAt entry.function "`get \"{path}\"` requires a read-only operation, but `{f}` returns `Op` (read-write); make it a `ReadOp` or use `post`"
  | .post, .query => throwErrorAt entry.function "`post \"{path}\"` publishes a read-write operation, but `{f}` returns `ReadOp`; use `get`"
  | _, _ => pure ()
  unless path.startsWith "/" do throwErrorAt entry.path "an endpoint path must start with `/`"
  let arguments := shape.params.map (·.name.toString)
  for parameter in pathParameters path do
    match shape.params.find? (·.name.toString == parameter) with
    | none =>
      throwErrorAt entry.path "path parameter `:{parameter}` in \"{path}\" has no matching argument of `{f}` (arguments: {String.intercalate ", " arguments.toList})"
    | some p =>
      if p.actor then
        throwErrorAt entry.path "path parameter `:{parameter}` in \"{path}\" names the actor argument of `{f}`; the actor comes from the session"
      unless ← liftTermElabM (pathBindable p.type) do
        throwErrorAt entry.path "path parameter `:{parameter}` in \"{path}\" binds argument `{parameter} : {← liftTermElabM (ppExpr p.type)}` of `{f}`, which has no path codec (only `Ref T` arguments can come from the path)"
  let constant := apiName ++ .mkSimple f.getString!
  if (← getEnv).contains constant then
    throwErrorAt entry.function "`{f.getString!}` is listed twice in `{apiName}`"
  let full := Deriving.full
  let errorText ← liftTermElabM <| Deriving.sourceOf shape.error
  let outputText ← liftTermElabM <| Deriving.sourceOf shape.output
  let builder := match entry.method with | .get => "LeanApi.Core.Endpoint.get" | .post => "LeanApi.Core.Endpoint.post"
  let endpointType := "LeanApi.Core.Endpoint " ++ full (f ++ `Input) ++ " (" ++ errorText ++ ") (" ++ outputText ++ ")"
  let route := builder ++ " " ++ Deriving.quoted path ++ " " ++ full (f ++ `operation)
  let parameters := pathParameters path
  if parameters.isEmpty then
    Deriving.runCommand ("def " ++ full constant ++ " : " ++ endpointType ++ " := " ++ route)
    return constant
  -- Path parameters are arguments, in path order: `api.borrow book`.
  let unbound := constant ++ `endpoint
  Deriving.runCommand ("def " ++ full unbound ++ " : " ++ endpointType ++ " := " ++ route)
  let mut binders := ""
  let mut body := full unbound
  for parameter in parameters do
    let some p := shape.params.find? (·.name.toString == parameter) | unreachable!
    let typeText ← liftTermElabM <| Deriving.sourceOf p.type
    binders := binders ++ " (" ++ parameter ++ " : " ++ typeText ++ ")"
    body := "(" ++ body ++ ").bindPath " ++ Deriving.quoted parameter ++ " (Ontology.Wire.codec.encode " ++ parameter ++ ")"
  Deriving.runCommand ("def " ++ full constant ++ binders ++ " : " ++ endpointType ++ " := " ++ body)
  return unbound

/-- Elaborate `def api : Api := [post "/x" f, get "/y/:id" g, …]`. -/
def elabApi (mods : TSyntax ``Lean.Parser.Command.declModifiers) (name : Ident) (elems : Array Syntax) : CommandElabM Unit := do
  let mut entries := #[]
  for elem in elems do
    match ← parseEntry elem with
    | some entry => entries := entries.push entry
    | none => throwErrorAt elem "an `Api` lists endpoints `post \"/path\" f` or `get \"/path\" f`"
  let apiName := (← getCurrNamespace) ++ name.getId
  let mut seen : Array (Method × String) := #[]
  let mut constants := #[]
  for entry in entries do
    let key := (entry.method, entry.path.getString)
    if seen.contains key then throwErrorAt entry.path "duplicate route {entry.method.name} \"{entry.path.getString}\""
    seen := seen.push key
    constants := constants.push (← declareEntry apiName entry)
  let items : Array Term := constants.map fun c => ⟨mkIdent (`_root_ ++ c)⟩
  -- Parenthesized type: this generated declaration is not re-intercepted.
  elabCommand (← `($mods:declModifiers def $name : (LeanApi.Core.Api) := [$items,*]))

@[command_elab Lean.Parser.Command.declaration] def elabApiDeclaration : CommandElab := fun stx => do
  match stx with
  | `($mods:declModifiers def $name:ident : $type:ident := [$elems,*]) =>
    let isApi ← try
        let resolved ← liftCoreM <| realizeGlobalConstNoOverload type
        pure (resolved == ``LeanApi.Core.Api)
      catch _ => pure false
    unless isApi do throwUnsupportedSyntax
    elabApi mods name elems.getElems
  | _ => throwUnsupportedSyntax

end LeanApi.Core.Api
