import LeanDb.Model
import LeanContract.Operation

/-! # The operation IR

An operation (`Op ε α`, `ReadOp ε α`, `LeanApi.Core.Op`) is a `Flow`: the free monad over
`RequestF`, plus a domain failure channel (`fail`) and decided checks (`check`, behind
`require`). `RequestF` EMBEDS LeanDB's storage requests unchanged (`storage`, any
`LeanDb.Model.StorageRequest`) and adds only the operation-level requests: the clock (`now`)
and authentication (`hashPassword`, `verifyCredential`, `startSession`).

The resource family `Resources` extends LeanDB's `StorageResources` with one slot, `auth`: the
session storage of a profile entity. Model code (`DB`, `Query`) is written against
`portableStorage`, operations against `portableResources`; publication
(`LeanApi.Core.Publish`) generalizes an operation's body over the family, so a native
adapter runs the same body with real evidence. -/

namespace LeanApi.Core
open Ontology LeanDb.Model

/-- The operation layer's resource family: LeanDB's storage evidence, and the session storage
of a profile entity (`auth`, used by `Auth.startSession`). -/
structure Resources extends StorageResources where
  /-- Session storage anchored to the exact profile entity storage. -/
  auth : {T : Type} → entity T → Type 1 := fun _ => PUnit

/-- The portable operation family: no evidence. `Op`/`ReadOp` are written against it. -/
def portableResources : Resources := { toStorageResources := portableStorage, auth := fun _ => PUnit }

/-- Session storage evidence for profile entity `T` on the exact entity storage. -/
class HasAuthResource (family : Resources) (T : Type) (storage : family.entity T) where
  witness : family.auth storage

/- Named, like LeanDB's portable instances: publication abstracts exactly these constants.
The storage is typed at LeanDB's `portableStorage`, which is what `HasEntityResource` hands
out, so instance search matches it without unfolding `portableResources`. -/
instance portableAuth (storage : portableStorage.entity T) : HasAuthResource portableResources T storage :=
  ⟨PUnit.unit⟩

/-- The storage access an operation kind allows: a query reads one snapshot, a command
reads and writes. -/
def accessOf : Contract.OperationKind → Access
  | .query => .query
  | .command => .command

/-- Where an authored credential entity `C` keeps the profile it belongs to and its hash
(generated by `credential C.profileField C.hashField`). -/
structure CredentialLink (C P : Type) where
  identity : String
  profile : FieldPath C (Ref P)
  hash : FieldPath C PasswordHash

/-- One operation-level request. Storage steps are LeanDB's own requests, embedded. -/
inductive RequestF (resources : Resources) (Scope : Type) : Contract.OperationKind → Type → Type 1 where
  /-- The server's clock, sampled by the runtime (after writer admission for a command). -/
  | now {kind : Contract.OperationKind} : RequestF resources Scope kind Instant
  /-- A LeanDB storage request at the access this kind allows. -/
  | storage {kind : Contract.OperationKind} {A : Type}
      (request : StorageRequest resources.toStorageResources Scope (accessOf kind) A) :
      RequestF resources Scope kind A
  /- Authentication (DDD-LAPI-06, decision 4). The runtime prepares the KDF work of
  `hashPassword`/`verifyCredential` before writer admission (`FlowMetadata.kdf` names the
  input field each consumes) and answers them from that preparation in the transaction. -/
  | hashPassword (password : Password) : RequestF resources Scope .command PasswordHash
  /-- Decision 2: `profile = none` still does the (dummy) KDF work and returns `none`. -/
  | verifyCredential {T C : Type} [Entity T] [Entity C] (credentials : resources.entity C)
      (link : CredentialLink C T) (profile : Option (Row Scope T)) (password : Password) :
      RequestF resources Scope .command (Option (Ref T))
  | startSession {T : Type} [Entity T] (storage : resources.entity T) (authentication : resources.auth storage)
      (profile : Ref T) : RequestF resources Scope .command Session

abbrev Request (Scope : Type) (kind : Contract.OperationKind) (A : Type)
    (resources : Resources := portableResources) := RequestF resources Scope kind A

/-- The operation language: requests, a closed domain failure channel and decided checks.
A query cannot construct a write request: storage writes exist only at `.command`. -/
inductive FlowF (resources : Resources) (kind : Contract.OperationKind) (Scope Error : Type) : Type → Type 1 where
  | pure {A : Type} (value : A) : FlowF resources kind Scope Error A
  | bind {A B : Type} (value : FlowF resources kind Scope Error A) (next : A → FlowF resources kind Scope Error B) :
      FlowF resources kind Scope Error B
  | fail {A : Type} (error : Error) : FlowF resources kind Scope Error A
  | request {A : Type} (value : RequestF resources Scope kind A) : FlowF resources kind Scope Error A
  | check (proposition : Prop) (decision : Decidable proposition) (error : Error) :
      FlowF resources kind Scope Error (PLift proposition)

abbrev Flow (kind : Contract.OperationKind) (Scope Error A : Type)
    (resources : Resources := portableResources) := FlowF resources kind Scope Error A

namespace Flow
abbrev pure := @FlowF.pure
abbrev bind := @FlowF.bind
abbrev fail := @FlowF.fail
abbrev request := @FlowF.request
abbrev check := @FlowF.check
end Flow

variable {resources : Resources}

instance : Monad (FlowF resources k Scope Error) where
  pure := Flow.pure
  bind := Flow.bind

/-- How a backend answers each request, in monad `m`. Framework failures belong to `m`. -/
structure Algebra (m : Type → Type u) (kind : Contract.OperationKind) (Scope : Type)
    (resources : Resources := portableResources) where
  request : {A : Type} → RequestF resources Scope kind A → m A

/-- The one semantics of an operation: domain failures are `.error`, requests go to the
algebra. -/
def Flow.run {m : Type → Type u} [Monad m] (algebra : Algebra m k Scope resources) :
    Flow k Scope Error A resources → m (Except Error A)
  | .pure value => Pure.pure (.ok value)
  | .fail error => Pure.pure (.error error)
  | .request req => do return .ok (← algebra.request req)
  | .bind value next => do
    match ← Flow.run algebra value with
    | .error error => Pure.pure (.error error)
    | .ok value => Flow.run algebra (next value)
  | .check _ decision error =>
    match decision with
    | .isTrue proof => Pure.pure (.ok ⟨proof⟩)
    | .isFalse _ => Pure.pure (.error error)

abbrev FlowF.run := @Flow.run

/-- A callee's closed error type must be explicitly mapped; new alternatives break the map.
Requests never fail in the domain channel, so only `fail` and `check` change. -/
def Flow.mapError (map : E → F) : Flow k Scope E A resources → Flow k Scope F A resources
  | .pure value => .pure value
  | .fail error => .fail (map error)
  | .bind value next => .bind (Flow.mapError map value) (fun value => Flow.mapError map (next value))
  | .check p decision error => .check p decision (map error)
  | .request req => .request req
abbrev FlowF.mapError := @Flow.mapError

/-- Read requests embed into a writer transaction unchanged. -/
def RequestF.toCommand : RequestF resources Scope .query A → RequestF resources Scope .command A
  | .now => .now
  | .storage req => .storage (kind := .command) req.toCommand

/-- `ReadOp`/`Query` lift into `Op`: the same flow, run inside the writer. -/
def Flow.toCommand : Flow .query Scope E A resources → Flow .command Scope E A resources
  | .pure value => .pure value
  | .fail error => .fail error
  | .bind value next => .bind (Flow.toCommand value) (fun value => Flow.toCommand (next value))
  | .check p decision error => .check p decision error
  | .request req => .request req.toCommand
abbrev FlowF.toCommand := @Flow.toCommand

/-- Capture the domain failures of a flow as values, without a new IR node: every failure
source is structural (`fail`, `check`); requests never fail in the domain channel. -/
def Flow.capture : Flow k Scope E A resources → Flow k Scope E (Except E A) resources
  | .pure value => .pure (.ok value)
  | .fail error => .pure (.error error)
  | .bind value next => .bind (Flow.capture value) fun
      | .ok value => Flow.capture (next value)
      | .error error => .pure (.error error)
  | .check p decision error => match decision with
      | .isTrue proof => .pure (.ok ⟨proof⟩)
      | .isFalse _ => .pure (.error error)
  | .request req => .bind (.request req) (fun value => .pure (.ok value))

/-- `try … catch` for flows: same error type, effects before a caught failure persist. -/
def Flow.tryCatch (body : Flow k Scope E A resources) (handler : E → Flow k Scope E A resources) :
    Flow k Scope E A resources :=
  .bind (Flow.capture body) fun
    | .ok value => .pure value
    | .error error => handler error

/-- One step of a published operation's body, for inspection (`f.operation.metadata.nodes`). -/
structure NodeMetadata where
  kind : String
  effect : Contract.OperationKind
  detail : String
  failure : Option String := none
  fields : List String := []
  constraints : List String := []
  deriving Repr

/-- A KDF step an operation can reach, keyed by the request input field it consumes, so the
runtime can run it before writer admission (decision 4). -/
inductive KdfStep where
  | hash (field : String)
  | verify (field : String)
  deriving Repr, BEq, DecidableEq

structure FlowMetadata where
  identity : Contract.OperationId
  kind : Contract.OperationKind
  failures : List String
  source : String
  actor : String := "Unit"
  nodes : List NodeMetadata := []
  establishesSession : Bool := false
  kdf : List KdfStep := []
  deriving Repr

/-- A published operation: its public wire contract (`Contract.Operation`), the typed
capabilities its body demands, and its body generalized over the family. -/
structure Operation (kind : Contract.OperationKind) (Actor : Type → Type) (Input Output Error : Type) where
  contract : Contract.Operation kind Input Output Error
  Requirements : Resources → Type 1
  portable : Requirements portableResources
  bodyWithResources : {resources : Resources} → Requirements resources →
    {Scope : Type} → Actor Scope → Input → Flow kind Scope Error Output resources
  metadata : FlowMetadata

/-- The body at the portable family (in memory, `LeanApi.Core.Memory`). -/
def Operation.body (operation : Operation kind Actor Input Output Error) :
    {Scope : Type} → Actor Scope → Input → Flow kind Scope Error Output :=
  operation.bodyWithResources operation.portable

/-- Generated only for an input consisting of one nominal route reference. -/
class RouteInput (Input : Type) where
  Target : Type
  targetIdentity : HasTypeId Target
  parse : String → Validation Input
  reference : Input → Ref Target

end LeanApi.Core
