/-
  Tier-2 HTTP features (M7, DESIGN §5.3):

  * Conditional requests: `conditionalGet` answers `If-None-Match` with 304
    from the response's `ETag` (GET/HEAD) and `If-Match` with 412 for unsafe
    methods; `ifModifiedSince` compares `Last-Modified` exactly.
  * Rate limiting: token buckets keyed per client address, actor, or route.
  * Server-Sent Events: `sse` formats events; `sseRes` builds a response.
  * Tracing: W3C `traceparent` propagation (generate or continue a trace).
  * Caching / redirect helpers: `cacheControl`, `vary`.
-/
import LeanApi.Http.Middleware
import Std.Sync.Mutex

namespace LeanApi

/-! ## Conditional requests -/

/-- Entity tags from `If-None-Match` / `If-Match` (comma-separated, `W/` allowed). -/
def parseETags (v : String) : List String :=
  (v.splitOn ",").map fun t =>
    let t := t.trimAscii.toString
    if t.startsWith "W/" then (t.drop 2).toString else t

/-- Weak comparison: `W/"x"` matches `"x"`. -/
def etagMatches (header : String) (etag : String) : Bool :=
  let et := if etag.startsWith "W/" then (etag.drop 2).toString else etag
  let tags := parseETags header
  tags.contains "*" || tags.contains et

/-- For GET/HEAD: if the response has an `ETag` matched by `If-None-Match`,
    answer 304 with the validators and no body (RFC 9110 §13.1.2). For
    other methods, `If-None-Match` matching an existing entity is 412. -/
def conditionalGet : NamedMiddleware :=
  ⟨"conditionalGet", fun h req => do
    let res ← h req
    match req.header? "if-none-match", res.header? "etag" with
    | some inm, some et =>
      if res.status / 100 == 2 && etagMatches inm et then
        if req.method == .get || req.method == .head then
          let keep := ["etag", "cache-control", "vary", "expires", "content-location", "last-modified"]
          pure { status := 304, headers := res.headers.filter (keep.contains ·.1), body := .empty }
        else pure (Problem.make 412 (some "If-None-Match matched")).toRes
      else pure res
    | _, _ => pure res⟩

/-- Precondition check for unsafe methods against the current entity tag
    (the handler supplies it, typically from a revision). `none` when the
    request may proceed; 428 when `required` and `If-Match` is missing. -/
def checkIfMatch (req : Req) (current : Option String) (required : Bool := false) : Option Res :=
  match req.header? "if-match", current with
  | none, _ => if required then some (Problem.make 428 (some "If-Match is required")).toRes else none
  | some v, some et => if etagMatches v et then none else some (Problem.make 412 (some "precondition failed")).toRes
  | some v, none => if v.trimAscii.toString == "*" then some (Problem.make 412).toRes else some (Problem.make 412).toRes

/-- `If-Modified-Since` with an exact `Last-Modified` string match (dates are
    generated by the app in IMF-fixdate form, so equal strings mean equal instants). -/
def ifModifiedSince : NamedMiddleware :=
  ⟨"ifModifiedSince", fun h req => do
    let res ← h req
    match req.header? "if-modified-since", res.header? "last-modified", req.header? "if-none-match" with
    | some ims, some lm, none =>
      if (req.method == .get || req.method == .head) && res.status == 200 && ims == lm then
        pure { status := 304, headers := res.headers.filter (fun (k, _) => k == "last-modified" || k == "etag" || k == "cache-control"), body := .empty }
      else pure res
    | _, _, _ => pure res⟩

def Res.cacheControl (r : Res) (v : String) : Res := r.setHeader "cache-control" v
def Res.vary (r : Res) (h : String) : Res := r.addHeader "vary" h

/-! ## Rate limiting -/

structure Bucket where
  tokens : Float
  last : Nat

structure RateLimit where
  /-- Tokens added per second. -/
  rate : Float
  burst : Float
  private buckets : Std.Mutex (List (String × Bucket))

def RateLimit.new (perSecond : Float) (burst : Nat) : IO RateLimit := do
  return { rate := perSecond, burst := burst.toFloat, buckets := ← Std.Mutex.new [] }

/-- Take one token for `key` at `nowMs`; returns `(allowed, retryAfterSeconds)`. -/
def RateLimit.take (rl : RateLimit) (key : String) (nowMs : Nat) : IO (Bool × Nat) :=
  rl.buckets.atomically do
    let bs ← get
    let b := (bs.lookup key).getD { tokens := rl.burst, last := nowMs }
    let elapsed := (nowMs - b.last).toFloat / 1000.0
    let tokens := min rl.burst (b.tokens + elapsed * rl.rate)
    let (ok, tokens') := if tokens ≥ 1.0 then (true, tokens - 1.0) else (false, tokens)
    -- keep the table bounded: drop the oldest entries beyond 10k keys
    let rest := (bs.filter (·.1 != key)).take 10000
    set ((key, { tokens := tokens', last := nowMs }) :: rest)
    let wait := if ok then 0 else ((1.0 - tokens') / rl.rate).ceil.toUInt64.toNat
    return (ok, max wait (if ok then 0 else 1))

/-- 429 with `Retry-After` when the bucket for `keyOf req` is empty. -/
def rateLimit (rl : RateLimit) (keyOf : Req → String := fun r => r.clientAddr.getD "-")
    (clock : IO Nat := IO.monoMsNow) : NamedMiddleware :=
  ⟨"rateLimit", fun h req => do
    let (ok, wait) ← rl.take (keyOf req) (← clock)
    if ok then h req
    else pure ((Problem.make 429 (some "rate limit exceeded")).withHeader "retry-after" (toString wait)).toRes⟩

/-! ## Server-Sent Events -/

structure SseEvent where
  data : String
  event : Option String := none
  id : Option String := none
  retry : Option Nat := none

/-- Format one event (multi-line data becomes several `data:` lines). -/
def SseEvent.render (e : SseEvent) : String :=
  let head := (match e.event with | some n => s!"event: {n}\n" | none => "") ++
    (match e.id with | some i => s!"id: {i}\n" | none => "") ++
    (match e.retry with | some r => s!"retry: {r}\n" | none => "")
  head ++ String.join ((e.data.splitOn "\n").map (s!"data: {·}\n")) ++ "\n"

/-- A finite event stream as one response (buffered). -/
def sseRes (events : List SseEvent) : Res :=
  { status := 200
    headers := [("content-type", "text/event-stream"), ("cache-control", "no-cache")]
    body := (String.join (events.map SseEvent.render)).toUTF8 }

/-! ## Tracing (W3C trace context) -/

structure TraceParent where
  traceId : String
  parentId : String
  flags : String
  deriving Repr, BEq

private def isHex (s : String) (n : Nat) : Bool :=
  s.length == n && s.all fun c => c.isDigit || ('a' ≤ c && c ≤ 'f')

def TraceParent.parse (v : String) : Option TraceParent :=
  match v.trimAscii.toString.splitOn "-" with
  | ["00", t, p, f] =>
    if isHex t 32 && isHex p 16 && isHex f 2 && t != "".pushn '0' 32 && p != "".pushn '0' 16 then some ⟨t, p, f⟩ else none
  | _ => none

def TraceParent.render (t : TraceParent) : String := s!"00-{t.traceId}-{t.parentId}-{t.flags}"

private def randHex (bytes : Nat) : IO String := do
  let mut s := ""
  for _ in [0:bytes] do
    let b ← IO.rand 0 255
    let d := String.ofList (Nat.toDigits 16 b)
    s := s ++ (if d.length == 1 then "0" ++ d else d)
  return s

/-- Continue the incoming trace (or start one), give this request a new
    span id, expose both as locals (`trace-id`, `span-id`), and echo
    `traceparent` on the response. -/
def tracing : NamedMiddleware :=
  ⟨"tracing", fun h req => do
    let incoming := (req.header? "traceparent").bind TraceParent.parse
    let traceId ← match incoming with
      | some t => pure t.traceId
      | none => randHex 16
    let span ← randHex 8
    let flags := (incoming.map (·.flags)).getD "01"
    let req := (req.setLocal "trace-id" traceId).setLocal "span-id" span
    let req := match incoming with
      | some t => req.setLocal "parent-span-id" t.parentId
      | none => req
    let res ← h req
    pure (res.setHeader "traceparent" (TraceParent.render ⟨traceId, span, flags⟩))⟩

end LeanApi
