#!/usr/bin/env python3
"""Stage the Part 1 post's domain (`partiful_v2/Domain.lean`) for the API-only acceptance.

The post's files are read, never edited. `Domain.lean` is copied to
`.lake/partiful-api/Partiful/Domain.lean` with the milestone 3 imports (`LeanDb.Model` and
`LeanApi.Core` in place of `LeanApp.Core`); nothing else in it changes. The server entry,
`.lake/partiful-api/PartifulApi.lean`, serves its `api` with its credential and the
`guestList` migration, and (`unmigrated`) the same app without the migration, for the
refusal check. Pages return with LeanReact (phase 4).
Usage: python3 scripts/stage_partiful_api.py [PARTIFUL_V2_DIR]
"""
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
spec = Path(sys.argv[1] if len(sys.argv) > 1 else root.parent / 'domain_driven_development/partiful_v2').resolve()
out = root / '.lake/partiful-api'
(out / 'Partiful').mkdir(parents=True, exist_ok=True)
domain = (spec / 'Domain.lean').read_text()
assert domain.count('import LeanApp.Core\n') == 1 and domain.count('open LeanApp.Core\n') == 1, \
    'expected `import LeanApp.Core` and `open LeanApp.Core` once each'
domain = domain.replace('import LeanApp.Core\n', 'import LeanDb.Model\nimport LeanApi.Core\n')
domain = domain.replace('open LeanApp.Core\n', 'open LeanDb.Model LeanApi.Core\n')
target = out / 'Partiful/Domain.lean'
if not target.exists() or target.read_text() != domain:
    target.write_text(domain)
main = '''/- Generated by scripts/stage_partiful_api.py: the post's api, served without pages. -/
import Partiful.Domain
import LeanApi.Native
open LeanDb.Model LeanApi.Core

app% server where
  authentication := Person with Credential
  api := api
  migrations := [
    -- Parties created before `guestList` existed keep behaving as they did.
    addGuestList := Party.addField guestList (fill := .everyone)
  ]

/-- `migrate --check` and `migrate` need the process arguments. `unmigrated` is the same app
before its migration was written. -/
def main (args : List String) : IO UInt32 :=
  match args with
  | "unmigrated" :: rest => LeanApi.Native.NativeApp.main { server with migrations := [] } rest
  | _ => server.main args
'''
target = out / 'PartifulApi.lean'
if not target.exists() or target.read_text() != main:
    target.write_text(main)
print(out)
