#!/usr/bin/env python3
"""Stage the Part 1 post's domain (`Partiful/Domain.lean`) for the API-only acceptance.

The post's files are read, never edited. `Domain.lean` is copied unchanged to
`.lake/leanapi-partiful-fixture/LeanApiPartifulFixture/Domain.lean`; it imports only
`LeanDb.Model` and `LeanApi.Core`. The server entry, `LeanApiPartifulFixture/Server.lean`, serves its `api` with its
credential and the `guestList` migration, and (`unmigrated`) the same app without the
migration, for the refusal check. Pages are LeanReact's.

The module names are test-scoped: a library of leanapi claims its modules in every workspace
that requires leanapi, and an app's own `Partiful.*` must not have a second provider.
Usage: python3 scripts/stage_partiful_api.py [PARTIFUL_DIR]
"""
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
spec = Path(sys.argv[1] if len(sys.argv) > 1 else root.parent / 'domain_driven_development/Partiful').resolve()
out = root / '.lake/leanapi-partiful-fixture'
(out / 'LeanApiPartifulFixture').mkdir(parents=True, exist_ok=True)
domain = (spec / 'Domain.lean').read_text()
assert 'import LeanDb.Model\n' in domain and 'import LeanApi.Core\n' in domain, \
    'expected the post to import `LeanDb.Model` and `LeanApi.Core`'
target = out / 'LeanApiPartifulFixture/Domain.lean'
if not target.exists() or target.read_text() != domain:
    target.write_text(domain)
main = '''/- Generated by scripts/stage_partiful_api.py: the post's api, served without pages. -/
import LeanApiPartifulFixture.Domain
import LeanApi.Native
open LeanDb.Model LeanApi.Core

app% server where
  authentication := Person with Credential
  api := api
  migrations := [
    -- Parties created before `guestList` existed keep behaving as they did.
    addGuestList := Party.addField guestList (fill := .everyone)
  ]

/-- `migrate --check` and `migrate` need the process arguments. `unmigrated` is the same app
before its migration was written. -/
def main (args : List String) : IO UInt32 :=
  match args with
  | "unmigrated" :: rest => LeanApi.Native.NativeApp.main { server with migrations := [] } rest
  | _ => server.main args
'''
target = out / 'LeanApiPartifulFixture/Server.lean'
if not target.exists() or target.read_text() != main:
    target.write_text(main)
print(out)
